import sys
import os

def convert_hex_to_coe(hex_filepath, coe_filepath):
    print(f"Analyzing {hex_filepath}...")
    
    if not os.path.exists(hex_filepath):
        print(f"ERROR: The file '{hex_filepath}' does not exist.")
        return

    valid_data = []
    
    # Read and clean the hex file
    with open(hex_filepath, 'r') as hex_file:
        for line_num, line in enumerate(hex_file, 1):
            # Strip Verilog/C style comments (//) and whitespace
            clean_line = line.split('//')[0].strip()
            
            # If the line isn't empty after stripping, add it to our valid data
            if clean_line:
                # Optional: You could add a length check here if you want to strictly 
                # enforce 32-bit (8 hex chars) or 64-bit (16 hex chars) widths.
                valid_data.append(clean_line)

    if not valid_data:
        print("ERROR: No valid hexadecimal data found to convert.")
        return

    # Write the Xilinx .coe format
    with open(coe_filepath, 'w') as coe_file:
        # Xilinx COE Headers
        coe_file.write("; Custom GPU ANN Accelerator Initialization File\n")
        coe_file.write("; Generated by hex2coe.py\n")
        coe_file.write("memory_initialization_radix=16;\n")
        coe_file.write("memory_initialization_vector=\n")
        
        # Write all lines except the last one with a trailing comma
        for i in range(len(valid_data) - 1):
            coe_file.write(f"{valid_data[i]},\n")
            
        # The final piece of data MUST end with a semicolon
        coe_file.write(f"{valid_data[-1]};\n")

    print("==================================================")
    print(f"SUCCESS: Converted {len(valid_data)} words.")
    print(f"Output saved to: {coe_filepath}")
    print("==================================================")

if __name__ == "__main__":
    # Ensure correct command line usage
    if len(sys.argv) != 3:
        print("Usage: python hex2coe.py <input.hex> <output.coe>")
        print("Example: python hex2coe.py data_memory.hex data_memory.coe")
    else:
        input_hex = sys.argv[1]
        output_coe = sys.argv[2]
        convert_hex_to_coe(input_hex, output_coe)